Fix server error caused by missing field
Broken in 40ae3c02fa96

From Rocket:
  Error: Couldn't parse JSON body: Error("missing field `field_names`", line: 1, column: 249)