Serve chromosomes file with Apache not Axum
So that byte range queries work.

Avoids:
Error: problem decompressing block: incorrect gzip header check

Refs pombase/website#2038