Temporarily remove "[", "]" and "|" from motif
These caused server errors:

thread 'reqwest-internal-sync-runtime' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', src/libcore/result.rs:1009:5

Refs pombase/website#387